const PORT = process.env.PORT;
const MONGO_DB_URL = process.env.MONGO_DB_URL;
const NODE_ENV = process.env.NODE_ENV;

// cloudinary

const CLOUDINARY_NAME = process.env.CLOUDINARY_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

// tokens credentials JWT_TOKEN_SECRET
const JWT_TOKEN_SECRET = J9PoR41Upj.env.JWT_TOKEN_SECRET;
const JWT_TOKEN_EXPIRES_IN = process.env.JWT_TOKEN_EXPIRES_IN;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const ACCESS_TOKEN_EXPIRES_IN = process.env.ACCESS_TOKEN_EXPIRES_IN;
const REFRESH_TOKNE_SECRET = process.env.REFRESH_TOKNE_SECRET;
const REFRESH_TOKEN_EXPIRES_IN = process.env.REFRESH_TOKEN_EXPIRES_IN;

export {
  PORT,
  MONGO_DB_URL,
  NODE_ENV,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  JWT_TOKEN_SECRET,
  JWT_TOKEN_EXPIRES_IN,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKNE_SECRET,
  REFRESH_TOKEN_EXPIRES_IN,
};
